# Generated by Django 4.2 on 2023-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventman", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("page_url", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Hero",
        ),
    ]
