# Generated by Django 4.2 on 2023-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventman", "0002_formsubmission_delete_hero"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsubmission",
            name="slug",
            field=models.SlugField(default="sample", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
