# Generated by Django 4.2 on 2023-04-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventman", "0004_remove_formsubmission_slug_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formsubmission",
            old_name="page_url",
            new_name="url",
        ),
    ]
